spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      stat-view-servlet:
        login-username: root
        login-password: 1234
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  #redis
  redis:
    database: 0
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 0
  jackson:
   date-format: yyyy-MM-dd HH:mm:ss
   time-zone: GMT+8
  cache:
    type: redis
#MongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/test