spring:
  profiles:
    active: dev
  application:
    name: com.li.controller
  datasource:
    url: jdbc:mysql://${mysqlServer.ip}:${mysqlServer.port}/spring_boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&allowMultiQueries=true
    username: ${mysqlServer.name}
    password: ${mysqlServer.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      stat-view-servlet:
        login-username: root
        login-password: 1234
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  #redis
  redis:
    database: 0
    host: ${redisServer.ip}
    port: ${redisServer.port}
    password: ${redisServer.password}
    pool:

    jedis:
      pool:
        max-idle: 8
        max-wait:
        min-idle: 0

  jackson:
   date-format: yyyy-MM-dd HH:mm:ss
   time-zone: GMT+8
  cache:
    type: redis
#MongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
#Mybatis
mybatis:
  type-aliases-package: com.li.domain
  configuration:
    map-underscore-to-camel-case: true
